### PR TITLE
Handle read for UPP identifiers.

### PR DESCRIPTION
**Pull request by BerniVarga**

### CODE REVIEW

**Comment by tosan88** [comment]
:+1:

**Comment by duffj** [comment]
@BerniVarga - shouldn't we be handling UUIDs using a library like https://github.com/satori/go.uuid ?

**Comment by tosan88** [comment]
@duffj is this necessary? what was changed on that part? if no changes on uuid part I'd rather create a separate PR for changing that library usage

**Comment by nwrigh** [comment]
:+1:

**Pull request merged**
